services:
  postgres:
    image: postgres:18
    container_name: task_postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: tmsnextnest
      POSTGRES_DB: taskmgmtdb
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: task_redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: